### ISSUE TITLE
Add sequel pro spf file generator command

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#107]
While it's possible to use the CLI command to interact with the database it'd be good to support connecting sequel pro in an easy way.

We could also consider Windows alternatives like MySQL workbench.

Props @ntwb for the suggestion.

**Comment by ntwb** [comment]
Also, this VS Code extension is something I'm hoping will continue to improve

https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/1016458/70676301-daa8c600-1cdf-11ea-87a5-0a0fa150f2bc.png">

**Comment by roborourke** [comment]
Nice find :) Guess a simple command to get db connection details is step one then.

**Comment by ntwb** [comment]
No SSH connections available in that VS Code extension, for now, sadly 😢

https://github.com/mtxr/vscode-sqltools/issues/230

(Its planned, so there is, some hope)

**Comment by BronsonQuick** [comment]
Related: #1 😉

**Comment by roborourke** [comment]
🤦‍♂️ Closing as dupe of #1
