### ISSUE TITLE
Escaping issues with exec command arguments containing spaces

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#113]
If you run something like `composer server cli -- db query 'select * from wp_posts;'` you get an error saying "Too many positional arguments". You have to add backslashes before the spaces for it to work.

This should just work ideally - I'm not sure if there are cases other SQL queries where this behaviour would be good to have but it's likely. If we can at least handle escaping spaces in anything between quotes it would fix this issue and for other commands that accept strings as arguments.

**Comment by roborourke** [comment]
Work in progress on #121

**Comment by shadyvb** [comment]
I can't replicate this on master anymore, using the example in OP, and the following example as well:

```shell
composer server cli -- db query --url='altis.dev' 'select id, post_title from wp_posts where post_title like "%test%";'
```

Am I missing an edge case or has this been magically fixed by something else ?

**Comment by rmccue** [comment]
Can we test explicitly with the `*` character as well? My assumption is that this is getting expanded by Bash expansion to file names, and it's this that's causing the error.

**Comment by shadyvb** [comment]
This is still working as expected with the `*` character. So can't use that to replicate the reported bug. cc @roborourke

**Comment by roborourke** [comment]
Might be shell specific then. What shell do you use?

**Comment by shadyvb** [comment]
I tried fish, bash, and zsh, all seems to work for `composer server cli -- db query 'select * from wp_posts;'` query.

**Comment by shadyvb** [comment]
@roborourke are you saying you are still having the same issue ?

**Comment by roborourke** [comment]
No I just thought that might been the last variable at play here. I think we can close this out now!
