### ISSUE TITLE
Running cli command db import with STDIN doesn't work

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#114]
Our documented solution to import a db here https://www.altis-dxp.com/resources/docs/local-server/cli/#wp-cli doesn't work currently.

If you run `composer server cli -- db import - < database.sql` you get logged into mysql on the db container instead. This isn't the expected behaviour! The WP CLI import command should run properly instead.

**Comment by roborourke** [comment]
Note, removing pseudo-terminal allocation (`-t`) from the `docker exec` call in this instance fixes the problem.

@joehoyle @rmccue I'm not super familiar with this aspect of WP CLI, the `isPiped` detection and TTY allocation. Is `<` and edge case that we need to handle specially or is the logic in PHP at fault?

**Comment by svandragt** [comment]
The [Running CLI commands Altis documentation page](https://www.altis-dxp.com/resources/docs/local-server/cli/) exhibits this problem, so it's likely people run into this.

As @roborourke mentioned:
> if the db dump is in the working directory then it’s available on the container and you can do `composer server cli -- db import database.sql`

**Comment by roborourke** [comment]
Related to #224

**Comment by rmccue** [comment]
If we can't get this closed out this sprint, let's reassess as it's been in here for a while.

**Comment by roborourke** [comment]
We actually updated the docs to explicitly say it needs to be within the project root, so the problem with the documented solution is fixed at least.

**Comment by rmccue** [comment]
So, no more bug? We can close?

**Comment by roborourke** [comment]
We can say it's not a supported use-case I guess, nothing else along these lines has really come up since. I'll close so we don't waste more time on it until there's more reasons to dig into TTY / piping-of-things support and use-cases.
