### ISSUE TITLE
Renew *.altis.dev certificate

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#126]
The certificate for *.altis.dev will expire on March 7, 2020. This cert is distributed with Local Server, so we need to register a new one, but also backport the update, as existing local installations will stop working if they don't update.

@rmccue how do you handle renewing the certs in Chassis, or is it a super long lived self-signed cert?

**Comment by roborourke** [comment]
@joehoyle for chassis it's generated during provision using the openssl extension, so yeah self signed.

Works well and provides flexibility. Separate issue really but relevant is that the single subdomain constraint of local server is one of the main things hurting its adoption by delivery teams.

**Comment by joehoyle** [comment]
> Separate issue really but relevant is that the single subdomain constraint of local server is one of the main things hurting its adoption by delivery teams.

Ah do we have a ticket for that? it would be easy to also support `*.*.altis.dev` on HTTPS atlesat.

> for chassis it's generated during provision using the openssl extension, so yeah self signed.

Ok - but what happens when it expires?

**Comment by roborourke** [comment]
> > for chassis it's generated during provision using the openssl extension, so yeah self signed.
> Ok - but what happens when it expires?

Delete it and re-provision? That's not really documented and oddly hasn't come up for anyone yet that I've seen. Getting away with it for the time being!

> Ah do we have a ticket for that? it would be easy to also support *.*.altis.dev on HTTPS at least.

I thought we couldn't! That'd be sweet, I added an issue for it here #135

**Comment by roborourke** [comment]
Fixed in #136
