### ISSUE TITLE
Add ability to map uploads folder

### ISSUE THREAD

**Issue by stuartshields** [humanmade/altis-local-server#140]
@roborourke Let me see if I can explain this properly for what I _think_ is needed with local-server.

So the other day I needed to access the uploads folder inside of s3 docker, however because this isn't mapped to any folder on the host machine. I had to go and change the docker yml file locally, to map it to the uploads folder on the host machine.

My recommendation here is that do the same thing by default: Map the S3 docker instance to the uploads folder, so we have access to the contents inside the uploads folder. This gives the developer the ability to add assets when using assets from production etc.

Hopefully this makes sense, happy to discuss further.

**Comment by roborourke** [comment]
Yeah I had wanted to use minio to provide this in the past as it has a file sync feature. The problem was that fake S3 doesn’t use a regular file structure for storage (more of a database) so it didn’t work to just mount the volume at the time.

If it’s that simple and works then great, we should definitely do this!

**Comment by roborourke** [comment]
Can you show me what you did? I just tried this and it's as I suspected the real file structure is like this:

```
└── uploads
    ├── 2020
    │   └── 03
    │       └── Screenshot-2020-03-04-16.37.29.png
    │           └── .fakes3_metadataFFF
    │               ├── content
    │               └── metadata
```

The `content` file in the `Screenshot-2020-03-04-16.37.29.png` directory is a binary blob and as such can't be opened properly locally without modifying the file name.

I think we'd need to look at switching to minio and using the sync feature to keep the uploads directory in sync. This is what I had to do for the `chassis-minio` extension when I needed to work on S3-Uploads previously.

**Comment by stuartshields** [comment]
@roborourke I ran into the same issue, because time is critical I went back to using Chassis instead. Your idea for minio sounds like the best way forward.

**Comment by roborourke** [comment]
In terms of adding assets it could perhaps be done using the s3 cli commands. Will see if it's something we can at least document in the interim.

**Comment by goldenapples** [comment]
@stuartshields Were you looking at the same issue here I was in #142? If so, the CLI command that ended up getting me unstuck might also be of use for you...

**Comment by roborourke** [comment]
@goldenapples @stuartshields I've opened #145 which sort of solves this. I was hoping to get bi-directional sync working with minio (alternative to fakes3) however it was a bit fraught. What that PR does do however is the following:

- Syncs S3 to the host's `content/uploads` directory automatically and continuously
- Adds a `composer server import-uploads` command to sync files from `/content/uploads` into S3

Does that seem satisfactory as a solution? I think we'll still need to write some guides for importing existing data and uploads into both environments regardless.
