### ISSUE TITLE
Document the process of importing uploads to FakeS3 for use in Tachyon

### ISSUE THREAD

**Issue by goldenapples** [humanmade/altis-local-server#142]
I [asked on Slack earlier](https://hmn.slack.com/archives/C3CKS8LLR/p1584464726497000) about help troubleshooting Tachyon images in my local-server install, where a uploads directory I had copied into my `/content` directory from a production export were not available in Tachyon.

The part of the process which I didn't understand beforehand was that the `content/uploads` directory isn't automatically synced to the fake s3 service container which tachyon accesses. I was able to "upload" my uploads directory by running `s3-uploads upload-directory`:

```
composer server cli -- s3-uploads upload-directory content/uploads
```

This would be good to explain in the documentation. I'll come back to do this soon, just leaving a note here for myself.

--------------

Acceptance criteria:

- [ ] Section added to troubleshooting with the title "Files in uploads directory not available via Tachyon or direct URL" with an explanation of why and the command to run

**Comment by roborourke** [comment]
I think we're going to want a full guide for importing existing data for both local envs. Will add separate issues in the docs repo for that.

**Comment by roborourke** [comment]
Since moving to Minio we've added commands to help with upload imports and documented those so we can close this one out now.
