### ISSUE TITLE
File permission issue on Linux

### ISSUE THREAD

**Issue by kucrut** [humanmade/altis-local-server#176]
Can't seem to be able to install themes/plugins via CLI with this error:

```sh
>>> $ composer server cli -- theme install twentynineteen
Installing Twenty Nineteen (1.6)
Downloading installation package from https://downloads.wordpress.org/theme/twentynineteen.1.6.zip...
The authenticity of twentynineteen.1.6.zip could not be verified as no signature was found.
Unpacking the package...
Warning: Could not create directory.
Warning: The 'twentynineteen' theme could not be found.
Error: No themes installed.
```

On 4.0.0 RC 1, the `uploads` directory was created with the owner set to `root`. Changing the ownership to my user didn't fix it. On v3, the `uploads` directory wasn't created at all.

**Comment by roborourke** [comment]
I have seen this before - I got the error however it still downloaded successfully, maybe that has changed with the updated version of WP CLI since we updated the PHP container.

The cause is that the container doesn't have a writable WP CLI home directory so I think we might need to create a writable mount to the expected location.

**Comment by kadamwhite** [comment]
Probably related to #183

**Comment by roborourke** [comment]
This one is more to do with where on the server WP CLI is trying to write to I think rather than the issue you're seeing in #183. This one happens on all platforms.

**Comment by roborourke** [comment]
Not totally sure what's creating the uploads directory but ideally anything under the project directory should be writable regardless of where it's created. I misunderstood the issue at first so you're right @kadamwhite this is very related to #183

**Comment by roborourke** [comment]
There may still be warnings shown as the temp files can't be written to the server but this should work now that #183 is resolved. Feel free to reopen if this is not the case.
