### ISSUE TITLE
db sequel command does not work on Mac

### ISSUE THREAD

**Issue by Nikschavan** [humanmade/altis-local-server#191]
**Describe the bug**
The error I get is - `This command is only supported on MacOS, use composer server db info to see the database connection details.`

`php_uname( 's' )` returns `Darwin` for me, I am not sure if that is supposed to be different on Mac.

https://github.com/humanmade/altis-local-server/blob/016af65086fc36b2d3d9b8f796724cff3a6bec55/inc/composer/class-command.php#L488-L491

**Expected behavior**
Command to work on Mac, If I comment this if condition, the database is loaded in sequel pro.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.5

**Additional context**

**Comment by roborourke** [comment]
Ah this is a regression, the logic was reversed. I'll fix it asap.

**Comment by Nikschavan** [comment]
Thanks for the quick fix! much appreciated ❤️

**Comment by roborourke** [comment]
Released in 4.0.2 👍  - thanks for the bug report!
