### ISSUE TITLE
Shared folder performance slow on macOs hosts

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#204]
It's fairly well documented that the shared folder / mounted volumes are slow on docker-for-mac. See https://www.padok.fr/en/blog/docker-sync-osx-mounted-filesystem, https://docs.docker.com/docker-for-mac/osxfs-caching/, https://docs.docker.com/docker-for-mac/osxfs/.

We currently use the `:delegated` option in the `/usr/src/app` mount -- this is the best performance option Docker has. I've observed, even with that, file system latency is circa 10x slower than native access. The nature of Composer + WordPress applications is a _lot_ of filesystem access, as such the _majority_ of the load time on a fresh Altis install homepage load is filesystem access. A filesystem syscall is around 1microsocond natively, and about 10microseconds under the shared mount.

One possible solution to this is http://docker-sync.io/, which has been created to fix this limitation of Docker on Mac. I switched my local install to using it, and I achieved total load times of around 220ms (as quick as 180ms), compared to a typical 900ms when using macos docker mounts.

I don't exactly know the best solution here -- we might be able to support docker-sync when it is installed and available (and could be another reason to push ahead with https://github.com/humanmade/altis-local-server/pull/159

**Comment by roborourke** [comment]
Can you document the configuration and steps you used to set this up here? I've looked through the docs but not had time to really understand how to use it in relation to local server.

**Comment by jennybeaumont** [comment]
@joehoyle could you follow up here with Rob's inquiry above? thanks!

**Comment by joehoyle** [comment]
@roborourke I dont have a step by step as it also took me a good amount of experimenting around to get it functioning. The docs are not super clear, but I don't really have much help here, beyond me just putting the time into figuring it all out again!

**Comment by roborourke** [comment]
@joehoyle alright no worries, that can be a job for whoever picks up this task then! First off we need the docker-compose in PHP thing done
