### ISSUE TITLE
composer server logs with no arguments should print logging options

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-local-server#216]
Today I ran `composer server logs` with no arguments, and got a generic error:
![image](https://user-images.githubusercontent.com/442115/92517101-25f6f300-f1e4-11ea-888e-8393ff27829d.png)

I quickly realized I should have included `php` or `nginx` or such, but in the moment it was confusing, and I could see this tripping up developers who use Altis local-server. I propose we set up this command to log some help text in the event that no service name was provided.

If we're able to get an actual list of containers from PHP, great; but if not, even a hard-coded explanation would be useful.

**Comment by roborourke** [comment]
Yeah that's not ideal!

I honestly thought it just defaulted the `php` logs but I agree showing a list of options is a good shout, even better we could use the Symfony question helper to accept an answer from a multiple choice question:

https://symfony.com/doc/current/components/console/helpers/questionhelper.html#let-the-user-choose-from-a-list-of-answers
