### ISSUE TITLE
Add a Redis browser

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#219]
A Redis browser could be a useful debugging tool, and a bit more precise than `wp cache flush` for figuring out cache related bugs.

Redis Commander is an open source Node based web app for interacting with a Redis server. There is a Docker container available here that's easy to configure and add to our existing set up:

https://hub.docker.com/r/rediscommander/redis-commander

**Comment by rmccue** [comment]
I've not heard people clamouring for this, so closing out.
