### ISSUE TITLE
Increase Nginx timeouts to make Xdebug debugging easier

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-server#223]
When stepping through code with Xdebug you only have 60 seconds before the Nginx gateway times out with a 504. In Chassis these timeouts are increased by default so you can debug at your leisure and still see your page at the end of it. We should do the same on Altis Local Server.

Steps to reproduce:

1. `composer server start --xdebug`
2. Add a breakpoint in your code and then run it
3. Wait more than 60 seconds
4. Observe that a `504 Gateway Time-out` error shows in your browser while you're still debugging

[Relevant config file in Chassis](https://github.com/Chassis/Chassis/blob/main/puppet/modules/chassis/templates/site.nginx.conf.erb). I forget exactly _which_ of these timeouts is the one that needs to change which is probably why they were all YOLO changed.

**Comment by johnbillion** [comment]
I just noticed on Chassis these timeouts are either 900 or 300. On my local Nginx I've jacked them right up to 3000 because I don't see any reason not to.

**Comment by roborourke** [comment]
Bit harder to do this one because we're using the production container image. It could be done with an `nginx-addtions.conf` file perhaps but we currently don't have a way for that to only apply locally.

**Comment by johnbillion** [comment]
Just noting that this is a real pain when debugging locally, it'd be a productivity boost to greatly increase the timeout on local server.

**Comment by roborourke** [comment]
This could be more doable now that our nginx container is using 1.19 - it has a feature for substituting environment variables into config files at run time.

A reason not to do this is that it could obscure problems that will occur on cloud environments but not local. We should be able to make it conditional based on whether xdebug is active or not though.

**Comment by roborourke** [comment]
@johnbillion this will be in the v7 release now, I'm pretty sure local server v7 will be compatible with older Altis versions so you could opt in early.
