### ISSUE TITLE
Increase Xdebug limits

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-server#225]
[As mentioned in Slack](https://hmn.slack.com/archives/C03K3J34A/p1602247370318700), the limits in place for Xdebug such as the size of a value when `var_dump()`d also affect the size of those values when stepping through code with breakpoints. The size limit appears to be 1kb.

Not sure which settings need to be changed off the top of my head, needs investigation.

**Comment by roborourke** [comment]
This is being handled as part of the PHP 7.4 upgrade in #244

**Comment by roborourke** [comment]
Default limits have been increased, in the meantime I realised there's a link to the docs for passing xdebug settings as part of the configuration in vscode. These could also be set by adding `ini_set()` calls in `.config/load-early.php` during development. Xdebug is not installed in cloud environments so these would safe to commit if desired.

https://go.microsoft.com/fwlink/?linkid=830387

Closed by #244
