### ISSUE TITLE
Update Redis version to match production version

### ISSUE THREAD

**Issue by JulienMelissas** [humanmade/altis-local-server#234]
Steps to reproduce:
1. Run `composer install` on new Altis project
2. Start Altis server for the first time via `composer server start`
3. Altis server setup scripts installs Redis version 3.x

Since Altis is running a newer version of Redis in dev/production environments, the local server should probably match that version for dev/prod parity.

Acceptance criteria:
- [ ] Local Redis version is the same (major at least) version as in dev/production environments

**Comment by missjwo** [comment]
Local-Server is now using Redis 7.x
