### ISSUE TITLE
Consider bibendi/dip for inspiration

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-local-server#235]
A friend shared this tool and I thought it was cool: https://github.com/bibendi/dip. It's a cli tool that lets you run commands inside of docker-compose created containers, but without any prefix like `composer serve`. Here's the first bit of their README:

---

A command-line utility that gives the "native" interaction with applications configured with Docker Compose. It is for local development only. In practice, it creates the feeling that you work without containers.

Dip can be injected into the current shell (ZSH or Bash).

```
eval "$(dip console)"
```

After that we can type commands without dip prefix. For example:

```
<run-command> *any-args
compose *any-compose-arg
up <service>
down
provision
```

When we change the current directory, all shell aliases will be automatically removed. But when we enter back into a directory with a dip.yml file, then shell aliases will be renewed.

**Comment by roborourke** [comment]
Is this something we could package with local server? Or more of a recommendation / guide territory?

**Comment by nathanielks** [comment]
My initial thought was a recommendation for a source of inspiration. It looked like a cool project to take notes from!

**Comment by roborourke** [comment]
Going to close this out for now, it seems like something individuals could set up but I'm not super convinced about making things more magical by default. Once we've settled on a best practice more generally for an Altis CLI and Altis commands we could look into it again.
