### ISSUE TITLE
*.altis.dev does not resolve on Ubuntu

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-local-server#250]
I've been working with @kadamwhite to discover why his local-server domains are not resolving. He uses Ubuntu for his desktop, which behaves differently than MacOS. The first step we did to see what may be wrong was using `dig` to see if ddit can resolve the address. `dig` surfaced that Ubuntu is using `127.0.0.1` as the DNS server on Ubuntu and is different than MacOS, which uses whatever is configured in the Network settings. I was able to replicate this behavior on an Ubuntu server: a fresh server uses the AWS-provided DNS server, but after setting up a local-server environment, dig uses `127.0.0.1`. I haven't yet been able to confirm if Traefik is changing DNS for some reason.

I'm putting this investigation on hold for right now until I can work more closely with @kadamwhite to isolate how this issue is triggered.

Steps to reproduce:
1. Unknown as of right now

Acceptance criteria:

- [ ] ...

**Comment by nathanielks** [comment]
Ugh, hit enter too soon. I'll add a comment here and then update the root comment.

`dig` surfaced that Ubuntu is using `127.0.0.1` as the DNS server on Ubuntu and is different than MacOS, which uses whatever is configured in the Network settings. I was able to replicate this behavior on an Ubuntu server: a fresh server uses the AWS-provided DNS server, but after setting up a local-server environment, dig uses `127.0.0.1`. I haven't yet been able to confirm if Traefik is changing DNS for some reason.

I'm putting this investigation on hold for right now until I can work more closely with @kadamwhite to isolate how this issue is triggered.

**Comment by roborourke** [comment]
@kadamwhite is this still an issue? Was there a workaround we should document in the troubleshooting guide?

**Comment by rmccue** [comment]
Closing as no reply.

**Comment by kadamwhite** [comment]
This doesn't appear to be an issue anymore, confirmed. I did a fresh Linux install and local server worked out of the box.
