### ISSUE TITLE
Shared services, like docker proxy, should not be destroyed by default when a destroy action is run

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-local-server#262]
When `composer server destroy` is called, `docker_proxy_1` is destroyed with the rest of the local server containers. However, if I have multiple environments on my local machine, that means that if I had another instance running, it will break.

As a developer, I expect my different environments to be kept separate, therefore I wouldn't expect one (running) environment to be affected by a `composer server destroy` action called on another environment.

**Proposed tactics**
* Default behavior leaves the `docker_proxy` shared container
* There could be a flag to specify a `--clean` destroy action, which removes all containers (including the proxy), e.g. `composer server destroy --clean`

**Comment by roborourke** [comment]
Noting here that this was done intentionally in #163 as the only to remove the proxy container was manually, see this comment on a related issue https://github.com/humanmade/altis-local-server/issues/70#issuecomment-651751791

I'd rather we look at detecting other running local server instances or containers using the proxy before removing it in a programmatic way if at all possible.

I'd also suggest that perhaps as well as having the flag option we could add a second question prompt to ask whether you want to destroy the proxy container too, and then act accordingly.

**Comment by kadamwhite** [comment]
> detecting other running local server instances

It's not just running, but also suspended servers, which I'd want to detect. I've gotten into trouble if the proxy got deleted while another server was suspended, in the past.

Could we ask Docker for a list of containers, and only remove the Proxy if we don't detect another one in the format we expect like `*_nginx_1`?
