### ISSUE TITLE
`composer server logs` does not work without a `<service>` parameter

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-local-server#270]
The docs for the `composer server logs` command states "Tail the logs from a given service, defaults to php". This is not the case as the command triggers an error when no service is provided.

Steps to reproduce:

1. `composer server logs`
2. Observe the following error:

       [ErrorException]
       Undefined offset: 0

**Comment by rmccue** [comment]
Duplicate of https://github.com/humanmade/altis-local-server/issues/216
