### ISSUE TITLE
Database commands are broken

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#364]
Possibly related to Docker Compose v2 and/or the new db container image.

- `composer server db` starts and then freezes, all input and output is swallowed (failed tty)?
- `composer server db sequel` and `composer server db info` fatal with an undefined array index error

**Comment by ntwb** [comment]
> - `composer server db` starts and then freezes, all input and output is swallowed (failed tty)?

Confirmed on both Intel & ARM64

> - `composer server db sequel` and `composer server db info` fatal with an undefined array index error

These both work fine for me on Intel, and both fail on ARM64

----
SSH'ing into the DB containers and running `printenv`:

|Intel|ARM64 v5.7|ARM64 v8.0|
|-----|-----|-|
|`HOSTNAME=eac7736938cd`|`HOSTNAME=0f313da13e38`|`HOSTNAME=d978c9a63c8b`|
|`MYSQL_MAJOR=5.7`|`MYSQL_MAJOR=5.7`||
|`HOME=/root`|`HOME=/root`|`HOME=/root`|
|`MYSQL_ROOT_PASSWORD=wordpress`|`MYSQL_ROOT_PASSWORD=wordpress`|`MYSQL_ROOT_PASSWORD=wordpress`|
|`TERM=xterm`|`TERM=xterm`|`TERM=xterm`|
|`MYSQL_PASSWORD=wordpress`|`MYSQL_PASSWORD=wordpress`|`MYSQL_PASSWORD=wordpress`|
|`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`|`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`|`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`|
|`MYSQL_VERSION=5.7.35-1debian10`|||
|`MYSQL_USER=wordpress`|`MYSQL_USER=wordpress`|`MYSQL_USER=wordpress`|
|`GOSU_VERSION=1.12`|`GOSU_VERSION=1.12`||
|`PWD=/`|`PWD=/`|`PWD=/`|
|`MYSQL_DATABASE=wordpress`|`MYSQL_DATABASE=wordpress`|`MYSQL_DATABASE=wordpress`|

The only difference is that on ARM64 `MYSQL_VERSION` is not available, this is the same for both the ARM64 versions of `biarms/mysql:5.7` and `mysql/mysql-server:8.0'` images I've tested (I'm using the v8 on my project)

So removing `MYSQL_VERSION` fixes this for ARM64, but unsure if this will impact Sequel Pro:

- https://github.com/humanmade/altis-local-server/blob/master/inc/composer/class-command.php#L556
- https://github.com/humanmade/altis-local-server/blob/master/inc/composer/class-command.php#L653
- https://github.com/humanmade/altis-local-server/blob/master/inc/composer/class-command.php#L568-L581

**Comment by roborourke** [comment]
Thanks for confirming, I have a PR to resolve it now.
