### ISSUE TITLE
Call to undefined function Altis\get_config()

### ISSUE THREAD

**Issue by kovshenin** [humanmade/altis-local-server#501]
One of the issues that's been popping off lately is this uncaught fatal error in Local Server:

```
Fatal error: Uncaught Error: Call to undefined function Altis\get_config() in /path/to/local-server/inc/composer/class-docker-compose-generator.php:843
Stack trace:
#0 /path/to/local-server/inc/composer/class-docker-compose-generator.php(89): Altis\Local_Server\Composer\Docker_Compose_Generator->get_config()
#1 /path/to/local-server/inc/composer/class-docker-compose-generator.php(205): Altis\Local_Server\Composer\Docker_Compose_Generator->get_php_reusable()
#2 /path/to/local-server/inc/composer/class-docker-compose-generator.php(718): Altis\Local_Server\Composer\Docker_Compose_Generator->get_service_php()
#3 /path/to/local-server/inc/composer/class-docker-compose-generator.php(829): Altis\Local_Server\Composer\Docker_Compose_Generator->get_array()
#4 /path/to/local-server/inc/composer/class-command.php(9 in /path/to/local-server/inc/composer/class-docker-compose-generator.php on line 843
```

I've been digging a bit more into this after seeing unit tests broken with Composer 1.x. This is the offending commit: 16260c7d65dad7e824b36db39f2e9d5244fdddaa where we went from reading the JSON file directly, to using a function defined in Altis Core. There's also #497 which was caused by the same commit, and could likely be solved by using the latest version of Composer and `altis/core`.

However, there is still a problem with Composer 1.x, as well as anything earlier than Composer 2.2.0, where the `files` section [used in the](https://github.com/humanmade/altis-core/blob/89d59f26918c017218b9def6af1a8b4e622d1123/composer.json#L20) `altis/core` autoload setting are not being loaded at all when running Composer plugins. This is a bug that seems to be fixed in Composer 2.2.0, here's the related PR: https://github.com/composer/composer/pull/10065

I was able to verify this by running `composer self-update 2.1.14` and still seeing the error upon `composer server start`.

Unless we're ready to drop support for Composer < 2.2.x we should look into fixing this. Classes autoloading still works as expected, so moving the `get_config()` logic into an `Altis\Config` class in altis/core may be an option. Another option would be to continue using `file_get_contents()`.

Acceptance criteria:

- [ ] `composer server start` works with Composer 1.x and 2.1.x

**Comment by roborourke** [comment]
> Another option would be to continue using file_get_contents().

It would need to mirror the behaviour of the core function if we were to go this route.

I would probably start by adding the core module as a dependency as that will affect the loading / processing order in composer. Problem is I'm not sure on how best to pin the versions in that situation.

Another workaround would be to move the config handling to another package that `altis/core` and `altis/local-server` require. One main reason for using the core module function was to avoid code duplication and to get consistency with how CI env specific configs and local configs could be treated, so that services could be switched on/off depending on which Altis features were being used.

**Comment by kovshenin** [comment]
> It would need to mirror the behaviour of the core function if we were to go this route.

I meant actually move it, not copy it. Then the functions in altis/core namespace.php can also use the new class, so everything referencing those functions will still work. Then in local-server we can use this class directly instead of trying to use the potentially undefined function, that would give us Composer <= 2.2.0 compatibility.
