### ISSUE TITLE
Update the 4-year-old version of Redis that we are using to the latest one

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-local-server#506]
The Redis image that is built for local server is version 3.2 -- over four years old.
That version isn't listed on thew Redis site (https://redis.io/download/) or even on Docker hub (https://hub.docker.com/_/redis).

The current version is 7.0. Looking through the release logs, it looks like multiple security fixes (though not necessarily present in 3.2) and speed improvements have been added to the newer version through the ages.

I presume this is local server only and we use some AWS up-to-date version on cloud.

#### Acceptance criteria

 - [x] update to the latest version of Redis
 - [x] update the version AWS too
 - [x] Test it!

**Comment by ferschubert-hm** [comment]
Just as reference on AWS we are using  5.0.6 as engine

**Comment by veselala** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-local-server/506?planning-poker) with Zenhub @ferschubert-hm @kovshenin @mikelittle @sivanovhm @wisyhambolu

**Comment by veselala** [comment]
@jerico we've estimated this one to 3 SP and moved it to the backlog.

**Comment by wisyhambolu** [comment]
## Local Server

The update of the local-server environment to use Redis 7.0 container image was successful. The info command shows the updated version

```
docker exec -it wisdom-inc-redis redis-cli INFO SERVER | grep redis_version
redis_version:7.0.7
``` 

### Test case 1 - Connectivity

The below shows a successful reply from the Redis server confirming connectivity was established

```
docker exec -it wisdom-inc-redis redis-cli
127.0.0.1:6379> PING
PONG
```

### Test case 2 - Addition of new site, confirmation of update in Redis

As seen below, there are currently only 2 site id entries (1 and 2)
```
docker exec -it wisdom-inc-redis redis-cli
127.0.0.1:6379> get sites:1
"O:8:\"stdClass\":12:{s:7:\"blog_id\";s:1:\"1\";s:7:\"site_id\";s:1:\"1\";s:6:\"domain\";s:20:\"wisdom-inc.altis.dev\";s:4:\"path\";s:1:\"/\";s:10:\"registered\";s:19:\"2023-01-12 10:02:30\";s:12:\"last_updated\";s:19:\"0000-00-00 00:00:00\";s:6:\"public\";s:1:\"1\";s:8:\"archived\";s:1:\"0\";s:6:\"mature\";s:1:\"0\";s:4:\"spam\";s:1:\"0\";s:7:\"deleted\";s:1:\"0\";s:7:\"lang_id\";s:1:\"0\";}"
127.0.0.1:6379> get sites:2
"O:8:\"stdClass\":12:{s:7:\"blog_id\";s:1:\"2\";s:7:\"site_id\";s:1:\"1\";s:6:\"domain\";s:20:\"wisdom-inc.altis.dev\";s:4:\"path\";s:6:\"/repo/\";s:10:\"registered\";s:19:\"2023-01-12 10:05:05\";s:12:\"last_updated\";s:19:\"2023-01-12 10:05:05\";s:6:\"public\";s:1:\"0\";s:8:\"archived\";s:1:\"0\";s:6:\"mature\";s:1:\"0\";s:4:\"spam\";s:1:\"0\";s:7:\"deleted\";s:1:\"0\";s:7:\"lang_id\";s:1:\"0\";}"
127.0.0.1:6379> get sites:3
(nil)
```

I added another site to confirm that Redis gets updated successfully

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/e93d38fc-39c0-4550-ad82-8a9feb0485fd)

The site was added successfully

```
wp site list --url=wisdom-inc.altis.dev 
+---------+------------------------------------------+---------------------+---------------------+
| blog_id | url                                      | last_updated        | registered          |
+---------+------------------------------------------+---------------------+---------------------+
| 1       | https://wisdom-inc.altis.dev/            | 0000-00-00 00:00:00 | 2023-01-12 10:02:30 |
| 2       | https://wisdom-inc.altis.dev/repo/       | 2023-01-12 10:05:05 | 2023-01-12 10:05:05 |
| 3       | https://secondsite.wisdom-inc.altis.dev/ | 2023-01-12 10:11:57 | 2023-01-12 10:11:57 |
+---------+------------------------------------------+---------------------+---------------------+
```

The entry for site id 3 was successfully updated in Redis

```
+---------+------------------------------------------+---------------------+---------------------+
| blog_id | url                                      | last_updated        | registered          |
+---------+------------------------------------------+---------------------+---------------------+
| 1       | https://wisdom-inc.altis.dev/            | 0000-00-00 00:00:00 | 2023-01-12 10:02:30 |
| 2       | https://wisdom-inc.altis.dev/repo/       | 2023-01-12 10:05:05 | 2023-01-12 10:05:05 |
| 3       | https://secondsite.wisdom-inc.altis.dev/ | 2023-01-12 10:11:57 | 2023-01-12 10:11:57 |
+---------+------------------------------------------+---------------------+---------------------+
```

### Test case 3 - Deletion of site, confirmation of update in Redis

I proceeded to delete the newly created site to confirm that Redis gets updated successfully

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/a648fd3a-37cf-4433-be87-62676182ce17)

The site was successfully deleted

```
wp site list --url=wisdom-inc.altis.dev 
+---------+------------------------------------+---------------------+---------------------+
| blog_id | url                                | last_updated        | registered          |
+---------+------------------------------------+---------------------+---------------------+
| 1       | https://wisdom-inc.altis.dev/      | 0000-00-00 00:00:00 | 2023-01-12 10:02:30 |
| 2       | https://wisdom-inc.altis.dev/repo/ | 2023-01-12 10:05:05 | 2023-01-12 10:05:05 |
+---------+------------------------------------+---------------------+---------------------+
```

The entry for site id 3 was successfully updated(deleted in this case) in Redis
```
127.0.0.1:6379> get sites:3
(nil)
```

**Comment by wisyhambolu** [comment]
## AWS Elasticache

I was successfully able to perform an in-place upgrade of Redis to v7.0. This took 7 minutes without any downtime.

Before update

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/1445687d-8ddc-4f2d-ac17-a92141a1900e)

The upgrade to v7 was completed successfully.

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/c6462db1-8b09-4aec-8fe1-5baef2757dd1)
The site loads as expected

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/2499cab3-9d88-47b3-86b7-d0117bab05af)

```
ubuntu@platform-test-sandbox--0d331eea6ab7dd831:~$ redis-cli -a XXXXXXXXXXXXXXXXXXXX INFO SERVER | grep redis_version
redis_version:7.0.5
``` 

### Test case 1 - Connectivity

The below shows a successful reply from the Redis server confirming connectivity was established

```
ubuntu@platform-test-sandbox--0d331eea6ab7dd831:~$ redis-cli -a XXXXXXXXXXXXXXXXXXXX
127.0.0.1:6379> PING
PONG
```

### Test case 2 - Addition of new site, confirmation of update in Redis

The highest site ID was previously 90, below confirms there was no site with id 91
```
127.0.0.1:6379> get sites:91
(nil)
```

I added another site to confirm that Redis gets updated successfully
![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/82dd0127-f0c9-404e-bbff-d00a4ad9028f)

The site was added successfully
![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/fa9d05df-1e01-40aa-ba29-684c7036a510)

The entry for site id 91 was successfully updated in Redis

```
127.0.0.1:6379> get sites:91
"O:8:\"stdClass\":12:{s:7:\"blog_id\";s:2:\"91\";s:7:\"site_id\";s:1:\"1\";s:6:\"domain\";s:31:\"wisdom.platform-test.aws.hmn.md\";s:4:\"path\";s:1:\"/\";s:10:\"registered\";s:19:\"2023-01-12 13:33:09\";s:12:\"last_updated\";s:19:\"2023-01-12 13:33:09\";s:6:\"public\";s:1:\"1\";s:8:\"archived\";s:1:\"0\";s:6:\"mature\";s:1:\"0\";s:4:\"spam\";s:1:\"0\";s:7:\"deleted\";s:1:\"0\";s:7:\"lang_id\";s:1:\"0\";}"
```

### Test case 3 - Deletion of site, confirmation of update in Redis

I proceeded to delete the newly created site to confirm that Redis gets updated successfully

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/cb594a8c-53b9-4f7e-a675-36c5b502393b)![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/a648fd3a-37cf-4433-be87-62676182ce17)

The site was successfully deleted

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/2e98cc93-a345-4d0a-adb1-b64ff5d08dc0)![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/4987161e-5a30-496a-a1f0-a41ea2a06d97)

The entry for site id 91 was successfully updated(deleted in this case) in Redis
```
127.0.0.1:6379> get sites:91
(nil)
```
