### ISSUE TITLE
docker compose should be docker-compose

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-local-server#564]
`docker compose` is meant to be `docker-compose` and on some Linux systems the `docker compose` backwards compat functionality is missing, causing local server to fail like this:

![image](https://user-images.githubusercontent.com/58855/215460404-7aeaea62-8d5f-4958-8a51-dedb646f3483.png)

This can be fixed by changing this line:

https://github.com/humanmade/altis-local-server/blob/de62107bcb8647a5cb017aa319de608eeb735136/inc/composer/class-command.php#L1232

**Comment by tomjn** [comment]
See: https://github.com/docker/compose/issues/8630

**Comment by rmccue** [comment]
This is not a bug.

Per [the docs](https://docs.docker.com/compose/reference/), this is needed for Compose v2 functionality:
> The new Compose V2, which supports the `compose` command as part of the Docker CLI, is now available.
>
> Compose V2 integrates compose functions into the Docker platform, continuing to support most of the previous `docker-compose` features and flags. You can run Compose V2 by replacing the hyphen (`-`) with a space, using `docker compose`, instead of `docker-compose`.
