### ISSUE TITLE
SSL Troubleshooting

### ISSUE THREAD

**Issue by tomjn** [humanmade/altis-local-server#567]
There is no mention of `mkcert` and SSL troubleshooting in the readme but especially on the Altis site:

 - what to do if you get an expired certificate error ( upgrade the package past v10 )
 - what to do if there is an invalid root certificate ( `composer server ssl exec -- -install` )
 - how to regenerate the certificate

**Comment by mikelittle** [comment]
Basic use of `mkcert` is documented on the [Local Server page ](https://docs.altis-dxp.com/local-server/#multisite-subdomains--custom-domains-support)
The issue of expired certificates no longer applies. 
But, the troubleshooting page could include a mention of using the `composer server ssl` command. Closing this issue but updating this issue https://github.com/humanmade/product-dev/issues/1669 to add a mention.
