### ISSUE TITLE
Update altis-local-server nginx image 

### ISSUE THREAD

**Issue by ferschubert-hm** [humanmade/altis-local-server#579]
### Description

Currently we are tracking on local-server the 3.4.0 nginx image https://github.com/humanmade/altis-local-server/blob/cc3f7c0ab86420e89784c2c54c274ae519a5c1ac/inc/composer/class-docker-compose-generator.php#L290

We are currently on [3.5.1](https://hub.docker.com/layers/humanmade/altis-local-server-nginx/3.5.1/images/sha256-34c14028bcaf52b177fa95ec188a2d3a33db33d38e14b453b33831be1e5dd01d?context=explore) 

### Acceptance Criteria

- [ ] Change altis-local-server to use the 3.5+ version from the nginx image

**Comment by kovshenin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-local-server/579?planning-poker) with Zenhub @jerico @mikelittle @wisyhambolu

**Comment by mikelittle** [comment]
Closed by https://github.com/humanmade/altis-local-server/pull/606
