### ISSUE TITLE
Kibana throws 500 error on a new install

### ISSUE THREAD

**Issue by wisyhambolu** [humanmade/altis-local-server#596]
### Description

On a fresh install of Altis 15 beta on the local server, the Kibana page throws a 500 error as seen below

![image.png](https://images.zenhubusercontent.com/601c4b38a237301d512d6e13/3ad82f93-5c31-4d50-a938-c132ab08da3e)

```
wisdom-org-kibana  | {"type":"log","@timestamp":"2023-04-13T15:23:33Z","tags":["error","http"],"pid":1,"message":"{ ResponseError: index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception\n    at IncomingMessage.response.on (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:272:25)\n    at IncomingMessage.emit (events.js:203:15)\n    at endReadableNT (_stream_readable.js:1145:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  name: 'ResponseError',\n  meta:\n   { body: { error: [Object], status: 429 },\n     statusCode: 429,\n     headers:\n      { 'x-opaque-id': '71df33a2-6b06-46f8-ba47-255092e83750',\n        'content-type': 'application/json; charset=UTF-8',\n        'content-length': '401' },\n     meta:\n      { context: null,\n        request: [Object],\n        name: 'elasticsearch-js',\n        connection: [Object],\n        attempts: 0,\n        aborted: false } },\n  isBoom: true,\n  isServer: false,\n  data: null,\n  output:\n   { statusCode: 429,\n     payload:\n      { message:\n         'index [.kibana_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];: cluster_block_exception',\n        statusCode: 429,\n        error: 'Too Many Requests' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/tooManyRequests' }"}
wisdom-org-kibana  | {"type":"error","@timestamp":"2023-04-13T15:23:33Z","tags":[],"pid":1,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:69:19)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:177:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":null,"query":{},"pathname":"/","path":"/","href":"/"},"message":"Internal Server Error"}
```

- [ ] Kibana page loads successfully with 200 response code on a new install.

**Comment by wisyhambolu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-local-server/596?planning-poker) with Zenhub @ferschubert-hm @jerico @kovshenin @mikelittle

**Comment by ferschubert-hm** [comment]
As mentioned in https://github.com/humanmade/product-dev/issues/1346 I could not reproduce this error, I could open Kibana properly (but I have tested after upgrading to 8.2). 

![image](https://user-images.githubusercontent.com/87646067/232575114-e1c3359d-9b73-47e8-bfd7-20d41a2385ac.png)

**Comment by jerico** [comment]
@wisyhambolu Same with Fernando, I also could not reproduce. Altis v15.0.0-beta.1 with PHP 8.2

**Comment by mikelittle** [comment]
This may be related to docker vm settings for cpu/ram/disk 

Or it could be one of those startup/timing related issues. The error message implies it was about a backlog "TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark" so it may be intermittent. A bit like the ES container cannot start 2 or 3 times out of 10 for me.

**Comment by wisyhambolu** [comment]
You're right @mikelittle. I just saw from the ES container logs that it was a disk space issue, my bad. I allocated more disk space Docker and it works fine now.

I'll proceed to close this issue.
