### ISSUE TITLE
Add debug.log to the logs command

### ISSUE THREAD

**Issue by chadaort** [humanmade/altis-local-server#66]
I'm currently ssh'ing into the machine to view wp logs. Can debug.log be added to the `composer local-server logs` command?

**Comment by joehoyle** [comment]
Hi @chadaort,

You can view the PHP logs with `composer local-server logs php`. That assumes you are not setting "logging to file" anywhere with `WP_DEBUG_LOG`.

**Comment by rmccue** [comment]
Going to close this out as it's not an active issue, but feel free to comment and we can reopen if needed.
