### ISSUE TITLE
Mailhog sometimes fails to start

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#67]
Sometimes when trying to start the local server I get:

```
Starting dev_mailhog_1 ... error

ERROR: for dev_mailhog_1  Cannot start service mailhog: b'Ports are not available: /forwards/expose/port returned unexpected status: 500'
```

Restarting Docker appears to fix it temporarily.

**Comment by roborourke** [comment]
I've seen that on and off with other containers. Usually to do with memory limits as Docker will just shut down a container sometimes if it hits the limit. Would be nice if it was possible to get notifications of that, or we add some `restart` settings to all the containers but have to be careful with that!

Not seen this exact issue myself yet at least.

**Comment by roborourke** [comment]
This was down to using the RC release of docker-compose, hopefully they'll resolve it their end but not much we can do right now.
