### ISSUE TITLE
Install fails when SUBDOMAIN_INSTALL is set

### ISSUE THREAD

**Issue by joehoyle** [humanmade/altis-local-server#68]
Because the install command is _not_ including `--subdomain`, it will install the blog as if it wernt, but if the constant is set to true, "weird" things happen.

Seems to be that for one, tables like wp_1_options etc get installed, and then the site can not be found too.

**Comment by roborourke** [comment]
Always wondered how that could happen! Seen this on other projects in the past :)

Should that constant be set at all if `WP_INSTALLING` is true though? Would be useful to have the context surrounding this.

**Comment by roborourke** [comment]
Possibly fixed by the changes to use `WP_INITIAL_INSTALL`, will test.

**Comment by roborourke** [comment]
So as long as `SUBDOMAIN_INSTALL` is only defined if `MULTISITE` is true or `WP_INITIAL_INSTALL` is not set then this is fine.

I think we should document in the migration guide that the `SUBDOMAIN_INSTALL` constant should be removed if we're not going to support it altogether.
