### ISSUE TITLE
Remove MySQL 5.7 support from local-server

### ISSUE THREAD

**Issue by wisyhambolu** [humanmade/altis-local-server#721]
### Description

Considering the fact that we are ending support for MySQL 5.7 on October 1st 2024; because that's also when AWS is ending standard support for that version; we should remove support for MySQL 5.7 from local-server to encourage people to opt for the migration to 8.0.

### Acceptance Criteria
- [x] MySQL 5.7 support is removed from local-server
- [x] The change is adequately documented with backup and upgrade information.

---

### Ready for Work Checklist

Is this ticket ready to be worked on? See
[the Play Book Definition of Ready](https://playbook.hmn.md/play/product/definition-of-ready/)

- [x] Is the title clear?
- [x] Is the description clear and detailed enough?
- [x] Are acceptance criteria listed?
- [x] Have any dependencies been identified? (Optional)
- [x] Have any documentation/playbook changes been identified? (Optional)
- [x] Is an estimate or time box assigned?
- [x] Is a priority label assigned?
- [x] Is this ticket added to a milestone?
- [ ] Is this ticket added to an epic? (Optional)

### Completion Checklist

Is this ticket done? See
[the Play Book Definition of Done](https://playbook.hmn.md/play/product/definition-of-done-2/)

- [ ] Has the acceptance criteria been met?
- [ ] Is the documentation updated (including README)?
- [ ] Do any code/documentation changes meet project standards?
- [ ] Are automatic tests in place to verify the fix or new functionality?
  - [ ] Or are manual tests documented (at least on this ticket)?
- [ ] Are any Playbook/Handbook pages updated?
- [ ] Has a new module release (patch/minor) been created/scheduled?
- [ ] Have the appropriate `backport` labels been added to the PR?

**Comment by mikelittle** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-local-server/721?planning-poker) with Zenhub @jerico @kovshenin

**Comment by mikelittle** [comment]
Release notes for when this change is released should be something like:

```markdown
## MySQL 5.7 no longer supported

Altis Local server no longer supports MySQL5.7. Running Local Server with this Altis version will run MySQL 8.0. Your database will automatically upgrade itself. As a precaution, before upgrading to this version, ensure you take a backup of your database. 

Also link to https://docs.altis-dxp.com/guides/upgrading/v19/#mysql-80-in-local-server
```
