### ISSUE TITLE
Traefik redirects to wrong backend

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-local-server#8]
When there are two sites, foo.example.dev and bar.example.dev, and submitting 2 requests to foo.example.dev, one of the requests will be served by bar.example.dev's backend but the url will be foo.example.dev. I've noticed this locally but haven't logged it anywhere, but it's something to figure out!

**Comment by nathanielks** [comment]
Another way of saying this is running multiple local servers at the same time won't work as expected as every 1/N requests will make it to the correct environment, where N is the number of environments currently running.

**Comment by joehoyle** [comment]
Hmm interested, I thought Traefik was set up with labels to direct the correct hostname to the correct container, or am I missing something?

**Comment by nathanielks** [comment]
Nope, you're assumption is correct! That's how I believe it's to be working, but it doesn't appear so!

**Comment by nathanielks** [comment]
I think I've figured it out. It may not be Traefik, after all. I've switched to using https://github.com/jwilder/nginx-proxy as that seems like a simpler implementation and I'm getting the same error. It then occurred to me that we're specifying backend as simply `php`. Because multiple environments are all on the same docker network, `php` refers to N backends, where is the number of environments running. Next up is to figure out how to get each `nginx` container to reference _its_ `php` container.

**Comment by nathanielks** [comment]
A simple test on the `nginx` container:
```
# curl -vv php
* Rebuilt URL to: php/
*   Trying 172.21.0.7...
* TCP_NODELAY set
* connect to 172.21.0.7 port 80 failed: Connection refused
*   Trying 172.21.0.13...
* TCP_NODELAY set
* connect to 172.21.0.13 port 80 failed: Connection refused
* Failed to connect to php port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to php port 80: Connection refused
```

`php` has multiple definitions, so it attempts to resolve each of them in the order they're defined.

**Comment by nathanielks** [comment]
Aha! Brilliant! The trick is to have _only_ the `nginx` container on the proxy network and then use the default network for everything, including the `nginx` container. This means the `nginx` container for the environment is both on the proxy network as well as the default network for that environment, meaning `php` will resolve to the `php` container on the default network 👍 💯

**Comment by roborourke** [comment]
Can the name `proxy` be dynamic eg. `"${COMPOSE_PROJECT_NAME}-proxy"`?

**Comment by nathanielks** [comment]
@roborourke nope, because there's a single instance of the proxy running:

https://github.com/humanmade/local-server/blob/7e600df2dc8c59c4c5d67a910272731e5da5a353/inc/Composer/Command.php#L66-L67

It's how we're able to get multiple projects running at once. What's the desired use case?

**Comment by roborourke** [comment]
Just trying to understand the issue!

**Comment by nathanielks** [comment]
Ah, gotcha! For better context:

> When there are two sites, foo.altis.dev and bar.altis.dev, and submitting 2 requests to foo.altis.dev, one of the requests will be served by bar.altis.dev's backend but the url will be foo.altis.dev.

> Another way of saying this is running multiple local servers at the same time won't work as expected as every 1/N requests will make it to the correct environment, where N is the number of environments currently running.

> This fixes this by placing each environment within their own network, and only placing nginx on both the proxy and environment networks. This enables the proxy to communicate with nginx, and nginx to route to the correct php container. If php isn't in its own network, nginx will route to the first php container registered.

> If we need to be able to expose these services outside of docker in a predictable way, it would be worth looking into service discovery solutions like Consul.

**Comment by nathanielks** [comment]
https://github.com/humanmade/local-server/pull/9 fixes this issue.
