### ISSUE TITLE
Alias "local-server" command to "server"

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-local-server#87]
Writing `composer local-server <command>` is needlessly long and the hyphen isn't great for quick tab completion.

Let's do two things:

- add an alias so we can write `composer server start`
- make `start` the default command so it's just `composer server`

**Comment by rmccue** [comment]
👌 

When we do this, let's also make sure `local-server` still works for back compat.

**Comment by roborourke** [comment]
`$this->setAliases( [ 'local-server' ] )`, easy!
